### ISSUE TITLE
running with sudo

### ISSUE THREAD

**Issue by acejacek** [hungnguyenm/edgemax-acme#3]
Running script with `sudo /config/scripts/renew.acme.sh` aborts `acme.sh` with this [message](https://github.com/Neilpang/acme.sh/wiki/sudo). Yet, root access is needed to start/stop services, etc. I see two choices:
1. Use `--force` to bypass warning.
2. Modify `renew.acme.sh` and deescalate authorisations to regular user. Path to log file must be altered, as regular user has no access to `/var/log/` Secondary problem is, that some dnsapi expect authorisation tokens in system variables (most notably _duckdns_). They have to be global variables, so they keep persistent across all users and shells.

**Comment by mentalinc** [comment]
Please merge this.
It enables certs to be created!

**Comment by hungnguyenm** [comment]
Hi all, sorry for the late response. I'd like to understand the use case a bit more. Generally, edgemax cronjob will run as root so the script is not a problem. Personally, for my routers, I use `root` with `sudo su` so it'd be consistent across sessions/users too. Would that work for you too?

Regarding the log file, I want to avoid using `ACMEHOME` to store the log files since it'll be persistent and eat up disk space (especially crucial for small devices like Edgerouter X). `/var/log` is ramfs so it'll be wiped during reboot.

**Comment by mentalinc** [comment]
Unfortunately the latest version of the acme script requires it and will
fail to run.
Expect your certs to expire the next time they attempt a renew.

This appears to be the only way.

You could add a cleanup script to reclaim space after a successful run, but
that's nice to have...

**Comment by hungnguyenm** [comment]
I don't think it'll complain if your shell is root, e.g., via `sudo su`. I just manually renewed one of my routers without problem. Something along this line:
```
# Switch to root user
sudo su
# Run the script as root without sudo
/config/scripts/renew.acme.sh -d subdomain.example.com ...
# Log out from root user
exit
```

**Comment by acejacek** [comment]
@hungnguyenm comment makes sense; when running as root, instead of `sudo config/scripts/renew.acme.sh -d subdomain.example.com ...` it all work OK. I revert back the change I did and validate, if taskscheduler will have any problems with it.

**Comment by hungnguyenm** [comment]
My routers were just able to renew the certs via cron recently so I hope this won't be an issue anymore :).
